language: node_js
node_js:
  - 16

cache:
  yarn: true
  directories:
    - "node_modules"

branches:
  only:
    - main

env:
  global:
    - DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/1186432608834441286/Uqhm8xarAkauIvr1-YXqAlKaRnDSX41GpO_zAAlGpss5h3FAN9mOpaWrhbaujqfR8Vp1"

install:
  - yarn install

matrix:
  fast_finish: true

jobs:
  include:
    - stage: build-and-ui-testing
      name: "Build and UI testing"
      script:
        - yarn build:prod
        - yarn storybook:build
        - yarn test:ui:ci
        - test:unit
    - stage: checks
      name: "Linting"
      script:
        - yarn lint:ts
        - yarn lint:scss
